apiVersion: batch/v1
kind: Job
metadata:
  name: airports
spec:
  template:
    spec:
      containers:
      - name: airports
        image: 10.0.0.130:5000/newdeploy
        command: ['java', '-jar', 'airports-assembly-1.0.1.jar']
      restartPolicy: OnFailure
